# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    labels:
      - "dependencies"
    reviewers:
      - "@Addepar/web-core"
    groups:
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
      Babel:
        applies-to: version-updates
        patterns:
          - "@babel/*"
      Embroider:
        applies-to: version-updates
        patterns:
          - "@embroider/*"
      Eslint:
        applies-to: version-updates
        patterns:
          - "@eslint/*"
          - "eslint-*"
      
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
    reviewers:
      - "@Addepar/web-core"
