packages:
  - vertical-collection
  - test-app

ignoreScripts: false
ignoreDepScripts: true
peersSuffixMaxLength: 40

autoInstallPeers: false
strictPeerDependents: true
dedupeInjectedDeps: true
dedupePeerDependents: true
resolvePeersFromWorkspaceRoot: false

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
  - sync
