packages:
  - vertical-collection
  - test-app

ignoreScripts: true
peersSuffixMaxLength: 40


autoInstallPeers: false
strictPeerDependents: true
dedupeInjectedDeps: true
dedupePeerDependents: true 
resolvePeersFromWorkspaceRoot: false

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
- build
- sync 

# Extra isolation for dependencies, even in spite of dep injection
sharedWorkspaceLockfile: false